name: Compilar Cemu PowerVR Fix
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Revisa si hay una version estable v5 
      with:
        submodules: recursive

    - name: Configurar Java 17
      uses: actions/setup-java@v5 
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalar Android SDK y NDK
      uses: android-actions/setup-android@v3 # verifica en su repositorio si hay una version mas nueva

    - name: Compilar APK Final
      run: |
        cd src/android
        chmod +x gradlew
        ./gradlew assembleRelease --no-daemon --stacktrace -Pandroid.skipSign=true

    - name: Subir APK Terminada
      uses: actions/upload-artifact@v4
      with:
        name: Cemu-PowerVRFix
        path: src/android/app/build/outputs/apk/release/*.apk
